### ISSUE TITLE
Change handling of dict

### ISSUE THREAD

**Issue by salabim** [nyggus/rounding#11]
I would prefer the following code to convert a dict (more compact, no explicit loops):

        if isinstance(value, dict):
            value.update({k, convert(v)})
            return value

**Comment by salabim** [comment]
This should read:
            value.update({k: convert(v) for k, v in value.items()})

**Comment by salabim** [comment]
Even better yet (at least more functional):

        if isinstance(value, dict):
            value.update(zip(value.keys(), convert(list(value.values()))))
            return value

**Comment by nyggus** [comment]
Done.
